version: '3.7'

services:
  postgres:
    container_name: postgres_solo
    build:
      context: ./database
    image: postgres-sio:1.0.0
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - webnetsolo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped

networks:
  webnetsolo:
    name: webnetsolo

volumes:
  pgdata:
    name: pgdata_solo
